AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: reporadar-${!Ref Environment}

Parameters:
  Environment:
    Type: String
  GitHubAccessToken:
    Type: String
Globals:
  Function:
    Timeout: 3

Resources:
  RepoRadar:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: reporadar/
      Handler: src/app.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RepoTable
      Environment:
        Variables:
          REPO_TABLE_NAME: !Ref RepoTable
          GITHUB_ACCESS_TOKEN: !Ref GitHubAccessToken
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 * * ? *)
            Enabled: True
            Input: '{ "query": "created:>2019-03-22 stars:>500 language:TypeScript sort:updated" }'

  RepoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      SSESpecification:
        SSEEnabled: true

Outputs:
  RepoTableName:
    Description: "Name of the DynamoDB database"
    Value: !Ref RepoTable
